namespace OElite
{
    public enum RestmeDbColumnType
    {
        NormalColumn = 0,
        ViewColumn = 10,

        NormalPrimaryKey = 100,
        AutoGeneratedPrimaryKey = 101,
        ForeignKey = 102,

    }
}